parameters:
#    atwix_hotkeys.example.class: Atwix\Bundle\HotkeysBundle\Example

services:
#    atwix_hotkeys.example:
#        class: %atwix_hotkeys.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
